### ISSUE TITLE
React and Venn.js, hover labels not appearing

### ISSUE THREAD

**Issue by AllanCodes** [benfred/venn.js#121]
Hello, I'm using venn js for my React application and I cannot seem to get the hover tooltip to show like in this example:
http://benfred.github.io/venn.js/examples/intersection_tooltip.html

I use this as the method of initiating it: `  var tooltip = d3.select("body").append("div")
      .attr("class", "venntooltip");`

However I've also tried replacing body with a 'div' I create and in that case it just places the tooltip at the bottom of the screen when hovering over regions.  Does anybody have experience with this in React that can point me in the right direction?

**Comment by benfred** [comment]
I don't have any experience with react here , but it sounds like you're missing the CSS in that example. 
Do you have something like this in the CSS ?
```css
.venntooltip {
  position: absolute;
  text-align: center;
  width: 128px;
  height: 16px;
  background: #333;
  color: #ddd;
  padding: 2px;
  border: 0px;
  border-radius: 8px;
  opacity: 0;
}
```
